### ISSUE TITLE
Joist might be relying on a pg 8.11.3 bug

### ISSUE THREAD

**Issue by brudil** [joist-orm/joist-orm#1019]
I've been spending today upgrading joist as we were a couple of versions back. Everything fine and dandy, except a couple of our tests were failing.

Looking in to it, some fields were coming back as `null`. This is a column that exists on a subtype of a CTI entity. It also appears in both subtypes. (Consider `Publisher` with both `SmallPublisher` and `LargePublisher` having a `location` column).

I assumed it might be a bug within the newly introduced STI support, but as I needed to move on I decided to revert the joist upgrade for the time being.

The tests still failed.

Working backwards seeing which other deps updated, I landed upon `pg` having gone from `8.11.3` to `8.11.4`.

Looking further, it looks like there is a "bug" within 8.11.3 which I think Joist might be relying on.

https://github.com/brianc/node-postgres/issues/3189

> selecting multiple columns with the same name would produce a non-null result if any of the columns were not null

Original bug report for 8.11.3; https://github.com/brianc/node-postgres/issues/3062

Now that pg will determanistically pick the last select for a given column name, the query generated will break for CTI clashes;
<img width="501" alt="image" src="https://github.com/joist-orm/joist-orm/assets/382352/c5cee028-ac02-4af9-a31a-151a60c0865e">

Always picking the last subtype selected for clashed columns

**Comment by brudil** [comment]
As this is such a low level change in pg, I don't think there are any toggles to restore behaviour. I haven't been in the joist internals in a while, but my guess here is that we would need to:

- Find shared column names across subtypes

- explictly define and alias them in the select

```sql
select "or".*, or_s0.*, or_s1.*, "or".id as id,
or_s0.location as s0_location, or_s1.location as s1_location
```

- merge using these columns from the returned `__class`

wdyt?

**Comment by stephenh** [comment]
Hi @brudil ! This is interesting! I appreciate the great diagnosis/already figuring out root cause. I also would have suspected the recent STI changes as the culprit. :-) 

Honestly, I'm not surprised columns-with-the-same-name-different-sub-types is broken, if anything I'm more surprised that a) is was working in the first place :-), and b) that the bug fix in pg (which makes sense) changed semantics that we were unwittingly relying on.

I think the separate location columns makes sense...

Would coalesce work too maybe? 

```
select "or".*, or_s0.*, or_s1.*, "or".id as id,
coalesce(or_s0.location, or_s1.location) as location
```

That might let the `em.hydate` code stay dumber/unaware of the subtype nuance...

I can probably take a crack at reproducing & fixing sometime in the next day or so, but lmk if you'd like to work on a PR for it. Thanks!

**Comment by stephenh** [comment]
@brudil I got a chance to add the explicit `COALESCE` and I think it's working; lmk if not/or you run into anything else while upgrading! Thanks!

**Comment by brudil** [comment]
You're too fast! Great shout to do it in pg via COALESCE. 

Cheers for this, I'll give it a whirl.

I'm currently attempting another for ESM attempt for our app - finally feel like like I might perhaps be getting somewhere...

**Comment by stephenh** [comment]
> I'm currently attempting another for ESM attempt for our app

Oh nice!

I'll be really curious to hear how it goes!

Honestly I'm a little nervous about having to support both CJS & ESM, just from the misc "gah this is terrible" blog posts that have gone by. :grimacing: But hopefully everyone else has figured out the gotchas by now. :crossed_fingers: :-)
