### ISSUE TITLE
esm, circular imports, await

### ISSUE THREAD

**Issue by brudil** [joist-orm/joist-orm#1031]
During our transition to esm, I hit a curious issue

<img width="714" alt="image" src="https://github.com/joist-orm/joist-orm/assets/382352/3b992ee7-94b2-44f7-a063-e8a52619529b">

I got this after moving a different package of ours to esm too. This module is imported within the entity (sync function that's used in a getter).

Thinking there had been more rabbit holes than an bunny after acupuncture, I hastily moved the package back to cjs and continued with the rest of the work. It has been in the back of my mind though - what could have been causing this?

To cut a boring story short - that package was importing Facebook's @lexical/headless. Our package moving to esm, obviously then starts utilising their esm builds. And that's when I saw something interesting.

The imported file:
```js
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
const mod = await (process.env.NODE_ENV === 'development' ?
  import('./LexicalHeadless.dev.mjs')
  : import('./LexicalHeadless.prod.mjs'));
export const createHeadlessEditor = mod.createHeadlessEditor;
```

That's a top-level await in the wild! This is when things started clicking around the nature of the error.

Enough that it's reproducable with

```ts
import {
  ContentEditorCodegen,
  contentEditorConfig as config,
} from './codegen/ContentEditorCodegen.js';

// Behold, Await, drama!
await new Promise<void>((r) => { r() });

export class ContentEditor extends ContentEditorCodegen {}

config.placeholder();
```

Now I know we're probably the first users of Joist in a ESM context, so I'm more than happy to continue hacking on this and playing around with this. We can workaround this issue in otherway in the meantime, so it's by no means a priority.

I think this will become a issue that will eventually need solving as more applications - and packages - start moving over.

Something interesting though - I've resolved this issue by changing metadata.ts to manually import ContentEditor (entity file with the promise)

```ts
// removed from big import from entities.ts

import { ContentEditor } from '../ContentEditor.js';
import { contentEditorConfig } from '../codegen/ContentEditorCodegen.js';
```

----

Questions for @stephenh if you've got time, I know there's the entities.ts file which explains it's purpose in fixing issues around circular importing. Any issues or gotchas should I look out for which have arrisen before re-circulars?

I'll see how this goes might it might be as simple as importing things slightly more directly within metadata.ts in esm mode.

**Comment by stephenh** [comment]
Interesting... so I guess there:

```
import {
  ContentEditorCodegen,
  contentEditorConfig as config,
} from './codegen/ContentEditorCodegen.js';

// Behold, Await, drama!
await new Promise<void>((r) => { r() });

export class ContentEditor extends ContentEditorCodegen {}

config.placeholder();
```

What's happening is that the `ContentEditor` symbol is exported from the module, and the "module init" finishes, but anything that reads `ContentEditor` before the `await` finishes will blow up.

...why were top-level awaits a good idea?... :thinking: :rofl: 

So my guess is that your PR #1032 fixes this because whatever top-level await got injected between `ContentEditor.js` loading-but-not-resolved somehow came from ...within the `entities.js` loading promise, so I guess it's actually the `ContentEditor from entities.js` symbol that is waiting to be resolved.

Can you tell where this `ContentEditor from entities.js`-is-waiting-to-be-resolved is coming from?

I'm pretty happy to ship #1032 as a "it works don't ask questions" work around :-D but also curious to learn what is keeping that `ContentEditor from entities.js` symbol to be readable.

Unless maybe this is just the new way module initialization works, like all of those `export * from ./...` lines that are above the `export * from ./codegen/metadata` are simply not referencable until `metadata.ts` itself finishes--except that doesn't seem right, b/c like `ContentEditor` is allowed to access `ContentEditorCodegen` via the `entities.js` symbol (and does so expressly to avoid the circular imports issue)...

:thinking: 

Dunno. Lmk if you can explain the behavior, but :shrug: yeah otherwise let's just ship #1032 :-)

**Comment by brudil** [comment]
Out of pure curiously I'll definitely be doing more research in to this. I know esm changes the semantics a fair bit.

Will report back what I find. I'm honestly a bit baffled it works too.
