### ISSUE TITLE
newPgConnectionConfig does not handle ssl settings specified in connection string

### ISSUE THREAD

**Issue by acgray** [joist-orm/joist-orm#1161]
`newPgConnectionConfig` currently does its own parsing of the DATABASE_URL here:

https://github.com/joist-orm/joist-orm/blob/004dad18dbeb69430fe66481ec39cc5f2354519c/packages/utils/src/connection.ts#L37-L48

This does not pass through any SSL options specified in the connection string (e.g. `sslmode=require`) and means it is impossible to use with any databases that require this, notably Vercel Postgres.

It would be good to at least handle `ssl=true` to mitigate this.

It seems to me given `createKnex` and the `Client` constructor from the `pg` module both already allow a connection string to be passed directly and handle SSL options correctly, it would be better just to pass the connection string directly in these cases?

The exception is `Pool` which requires an object.

I have made a very simple patch but by all means disregard if there is a better alternative.

**Comment by stephenh** [comment]
Hi @acgray -- you're right that we should probably just get out of the connection string parsing business all together, because there isn't really a reason for Joist to know about the internals.

This `connection.ts` is originally an extraction from our internal codebase, that sometimes picks/chooses different dbs (i.e. for running tests in parallel, we pick a different db name per jest worker) ... but yeah, we could probably handle this better / "dumber"-in-a-better way.

That said/for now, I just merged your PR; thank you! Definitely feel free to ping/open issues/ask in discord if you run into anything else.
